version: "3"
services:
  proxy:
    image: "ghcr.io/wooseongshin/proxy:latest"
    ports:
      - "80:80"
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
  react:
    image: "ghcr.io/wooseongshin/client:latest"
    restart: always
    build:
        dockerfile: Dockerfile
        context: ./client
  nest:
    image: "ghcr.io/wooseongshin/server:latest"
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./server

