version: "3"
services:
  proxy:
    image: "ghcr.io/wooseongshin/proxy:latest"
    ports:
      - "80:80"
    restart: always
  react:
    image: "ghcr.io/wooseongshin/client:latest"
    restart: always
  nest:
    image: "ghcr.io/wooseongshin/server:latest"
    restart: always
